// File generated by FlutterFire CLI (manually maintained for Bakaloo project).
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJqvLI-10Smy4kp3OwPX0Ooi46PFhOR8',
    appId: '1:802646854363:android:e903b3cfb80476f6665afe',
    messagingSenderId: '802646854363',
    projectId: 'bakaloo',
    storageBucket: 'bakaloo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJJqvLI-10Smy4kp3OwPX0Ooi46PFhOR8',
    appId: '1:802646854363:ios:e903b3cfb80476f6665afe',
    messagingSenderId: '802646854363',
    projectId: 'bakaloo',
    storageBucket: 'bakaloo.firebasestorage.app',
    iosBundleId: 'com.grolin.rider',
  );
}
